# Site settings
title: Horse Dragon Fish
email: horsedragonfish@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://horsedragonfish.com" # the base hostname & protocol for your site
twitter_username: horsedragonfish
github_username:  spaldos
facebook_page:  horsedragonfish

# Build settings
markdown: kramdown
permalink: pretty

host: 0.0.0.0

collections:
  comics:
    output: true
    permalink: /comics/:path/